### PR TITLE
Audio extraction from ROM

### PR DESCRIPTION
**Pull request by ckosmic**
Adds support for automatically extracting and parsing audio data.  Builds, untested with Retro64.

### CODE REVIEW

**Comment by Bloxxel64** [comment]
but it already does that

**Comment by ckosmic** [comment]
> but it already does that

Not without the use of genfiles.  This eliminates the requirement to extract audio data externally and instead does it directly in the library.

**Comment by Bloxxel64** [comment]
works fine without it for me

**Comment by ckosmic** [comment]
> works fine without it for me

Yes... with the way the Retro64Mod installer works it does this for you, however that's not the point of these changes.

**Comment by Bloxxel64** [comment]
what are they for?

**Comment by Bloxxel64** [comment]
also, installer?

**Pull request merged**
